---
containers_syncthing_docker_root_dir: "{{ docker_dir }}"
containers_syncthing_dir: "{{ containers_syncthing_docker_root_dir }}/syncthing"
containers_syncthing_enable_traefik: true
containers_syncthing_docker_network: "proxy"
