---
- name: Install Python and python3-pip
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
    state: present
  when: ansible_facts['distribution']  != 'Alpine'
  become: true

- name: Install docker module for Python
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose
  when: ansible_facts['distribution']  == 'Ubuntu'
  become: true

- name: Install python packages on Debian
  ansible.builtin.package:
    name:
      - python3-docker
    state: present
  when: ansible_facts['distribution']  == 'Debian'
  become: true
