---
roles:
  - name: geerlingguy.docker
  - name: geerlingguy.dotfiles
  - name: gantsign.visual-studio-code

collections:
  - name: community.docker
  - name: community.general
  - name: ansible.posix
  - name: prometheus.prometheus
  - source: https://github.com/galbitz/star4-essentials
    type: git
    version: main
  # collections:
  #   - source: /mnt/c/code/star4-essentials
  #     type: dir
  - name: grafana.grafana
