---
- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
  when: (ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution']  == 'Ubuntu') and (ansible_env['WSLENV'] is not defined)
  become: true

- name: Restart ssh (Redhat)
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  when: (ansible_facts['distribution']  == 'CentOS' or ansible_facts['distribution'] == 'Red Hat Enterprise Linux') and (ansible_env['WSLENV'] is not defined)
  become: true
