# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
- name: Check pre req
  ansible.builtin.assert:
    that:
      - containers_newt_id | length > 0
      - containers_newt_secret | length > 0
    fail_msg: "variable is missing"

- name: Make sure that the docker folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: u+rwx,g+rwx,o+rxw
  loop:
    - "{{ containers_newt_dir }}"
  become: true

- name: Copy docker compose
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ containers_newt_dir }}/compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u+rw,g+rw,o+rw
    force: true
  become: true

- name: Docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ containers_newt_dir }}"
  become: true
