---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
- name: Check pre req
  ansible.builtin.assert:
    that:
      - containers_silverbullet_docker_root_dir | length > 0
    fail_msg: "variable is missing. Define it in global vars"

- name: Ensuring folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: u+rwx,g+rwx,o+rxw
  loop:
    - "{{ containers_silverbullet_dir }}"
  become: true

- name: Copy files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: u+rwx,g+rwx,o+rxw
    force: true
  become: true
  loop:
    - src: compose.yaml.j2
      dest: "{{ containers_silverbullet_dir }}/compose.yaml"

- name: Docker-compose up
  community.docker.docker_compose_v2:
    project_src: "{{ containers_silverbullet_dir }}"
  become: true
