---
# find icons here: https://github.com/walkxcode/dashboard-icons
- Hypervisors:
    - Damage:
        href: https://damage.04a.ca:8006/
        icon: proxmox.png
    - Bone:
        href: https://bone.04a.ca:8006/
        icon: proxmox.png
    - Shadow:
        href: https://shadow.04a.ca:8006/
        icon: proxmox.png
    - Master:
        href: https://master.04a.ca:8006/
        icon: proxmox.png
- Services:
    - Beszel Hub:
        href: http://192.168.1.17:38090/
        icon: beszel.png
    - Home Assistant:
        href: https://ha.04a.ca/
        icon: home-assistant-alt.png
    - Guacamole (local):
        href: https://guacamole.home.04a.ca/
        icon: guacamole.png
    - Unifi wifi:
        href: https://unifi.ui.com/
        icon: unifi.png
    - Uptime Kuma:
        href: https://uptime.home.04a.ca/
        icon: uptime-kuma.png
    - Portainer:
        href: https://portainer.home.04a.ca/
        icon: portainer.png
    - Traefik (local):
        href: https://traefik.home.04a.ca/
        icon: traefik.png
    - Grafana (local):
        href: https://grafana.home.04a.ca/
        icon: grafana.png
    - Grafana (cloud):
        href: https://derive.grafana.net/a/grafana-setupguide-app/home
        icon: grafana.png
    - NUT:
        href: https://nut.home.04a.ca/ups/default/CP
        icon: ups.png
    - Switch:
        href: http://192.168.1.3/
        icon: mdi-switch
    - Netboot:
        href: http://192.168.1.17:3500/
        icon: netboot.png
    - Syncthing (local):
        href: http://localhost:8384/
        icon: syncthing.png
    - Syncthing (hosted):
        href: https://syncthing.pa.04a.ca/
        icon: syncthing.png
    - TrueNAS:
        href: https://truenas.04a.ca/
        icon: truenas.png
    - Qbittorrent:
        href: http://192.168.1.17:8085/
        icon: qbittorrent.png
    - SilverBullet:
        href: https://silverbullet.home.04a.ca/
        icon: silverbullet.png
    - Pangolin:
        href: https://pangolin.pa.04a.ca/
        icon: pangolin.png
    - SLZB:
        href: http://192.168.1.38/
        icon: zigbee2mqtt.png
